### ISSUE TITLE
Enchantment list bug

### ISSUE THREAD

**Issue by Ganondorf629** [Franckyi/ItemEditorGUI#1]
I can't see each enchant

**Comment by skyecodes** [comment]
Hmm, I need more informations : which version of the mod are you using ?

**Comment by Ganondorf629** [comment]
0.0.3.3

**Comment by skyecodes** [comment]
The enchantment list has a scroll bar, the only way to see all the list is to drag the scroll bar down. The mouse wheel will not work.
