### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Ganondorf629** [Franckyi/ItemEditorGUI#3]
The mod version 1.0.0 seems to not work on multiplayer server

**Comment by skyecodes** [comment]
What do you mean by "not working" ? Do you have a crash report ?

**Comment by Ganondorf629** [comment]
I mean the mod is detected by forge, the gui is working but nothing change when I wanna change item's name for example

**Comment by skyecodes** [comment]
You also have to install the mod on the server, that's probably the issue.
