### ISSUE TITLE
World crash when clicking "Exit Menu"

### ISSUE THREAD

**Issue by laserlemons** [Franckyi/ItemEditorGUI#6]
^ I get a crash to the main menu when I click the "Exit Menu" button in singleplayer. It's not a CTD so I don't have a crash log.

**Comment by skyecodes** [comment]
Forge version ? Mod version ? Steps to follow to reproduce the bug ?

**Comment by laserlemons** [comment]
Latest forge version in 1.11.12 (2226), latest mod version (0.1.0.0), press 'I' and click 'exit menu'. I haven't used the mod that much but I've had a friend tell me he's also experienced multiple other crashes while playing around with the UI.

**Comment by skyecodes** [comment]
I tried the same thing and everything is working. Last question, are you using Java 6, 7 or 8 ?
If you use 8, there should be no issue, launch your game with the console (Edit Profile, Launcher Visibility, Keep the Launcher open; run minecraft then when the world crashes, go in the Launcher Log and copy it. This is the only way I can know what's going on.

**Comment by laserlemons** [comment]
I'm not able to recreate it on my laptop. When I get home tomorrow I'll do it on my desktop where I originally got the crash. I'm using the latest version of Java 8 (101) and Windows 10 on both, and it's the same setup as the computer my friend is using.

**Comment by skyecodes** [comment]
Ok, thanks.

**Comment by laserlemons** [comment]
Well, this is awkward. Neither one of us is getting any crashes now. We haven't changed anything about the mod pack we were using either. If it happens again I'll open another issue with the crash log.

**Comment by skyecodes** [comment]
Thanks ;)
